services:
  - type: web
    name: yt-api
    runtime: node
    plan: free
    buildCommand: pip3 install yt-dlp && npm install
    startCommand: node server.js
    envVars:
      - key: POT_SERVER_URL
        value: https://pot-provider.onrender.com
