# render.yaml
services:
  - type: web
    name: yt-api
    runtime: node
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y python3 python3-pip
      pip3 install yt-dlp
      npm install
    startCommand: node server.js
    envVars:
      - key: POTOKEN_SERVER
        value: https://bgutil-ytdlp-pot-provider-rs-ayxn.onrender.com
